### ISSUE TITLE
"Type Error" when port parameter is not passed while calling setup_db

### ISSUE THREAD

**Issue by pradeepjnayak** [tranlyvu/wiki-link#28]
Default value of port parameter in "setup_db" function is of type integer, while it is expecting in string.
![port_string](https://user-images.githubusercontent.com/23418708/58571349-2a99d100-8257-11e9-9a3a-09ddb0694b56.png)

**Comment by tranlyvu** [comment]
resolved in https://github.com/tranlyvu/wiki-link/pull/30
